name: Cypress Tests

on: [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        with: # Set the secret as an input
          projectId: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
        env: # Or as an environment variable
          projectId: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
